version: 2
jobs:
  build:
    docker:
      - image: python:3.6
        environment:
          DATABASE_URL: postgresql://postgres:password@localhost:5432/postgres
          SHELL: /bin/bash
      - image: postgres:10.1
        environment:
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: "password"
          POSTGRES_DB: postgres
      - image: redis:4

    working_directory: ~/accounting

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Pipfile" }}
          - v1-dependencies-

      - run:
          name: Install Dependencies
          command: |
            pip install pipenv
            pipenv install --python 3.6

      - save_cache:
          paths:
            - pipenv --venv
          key: v1-dependencies-{{ checksum "Pipfile" }}

      - run:
          name: Run Tests
          command: |
            . $(pipenv --venv)/bin/activate
            make test

      - store_artifacts:
          path: test-reports
          destination: test-reports
